content:
  - name: home
    label: Home Page
    path: index.html
    type: file
    fields:
      - name: body
        type: rich-text

  - name: about
    label: About Page
    path: about.html
    type: file
    fields:
      - name: body
        type: rich-text
